"""Structural conventions, enforced so `docs/CONVENTIONS.md` stays true.

A conventions doc that nothing checks is a wish. These tests are the mechanism
that makes the library feel like one library: same directory shape, same
parameter interface, same documentation, same proof of testing — for template
number 4 and template number 40.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest
import yaml

from cfn_loader import Template, load_template

REPO_ROOT = Path(__file__).resolve().parent.parent

VALID_STATUSES = ("experimental", "beta", "stable")
REQUIRED_METADATA_KEYS = ("group", "status", "summary")
DOC_MARKERS = ("<!-- BEGIN_CFN_DOCS -->", "<!-- END_CFN_DOCS -->")

# CloudFormation's own hard limits. Hitting one at deploy time, after a
# 20-minute rollback, is a bad way to find out.
MAX_TEMPLATE_BYTES = 1_000_000
MAX_RESOURCES = 500
MAX_PARAMETERS = 200
MAX_OUTPUTS = 200


def _rel(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT))


# --- directory shape --------------------------------------------------------


def test_template_directory_is_self_contained(template_dir: Path) -> None:
    """A template directory carries everything needed to understand and use it.

    The point of co-locating docs, an example, and tests with the template is
    that a reader never has to go looking, and a reviewer can tell at a glance
    whether a PR is complete.
    """
    required = {
        "template.yaml": "the template itself",
        "metadata.yaml": "catalog entry (group, status, summary)",
        "README.md": "usage docs with generated parameter tables",
        "examples/basic/parameters.json": "a runnable example parameter set",
    }
    missing = [f"{name} ({why})" for name, why in required.items() if not (template_dir / name).exists()]
    assert not missing, f"{_rel(template_dir)} is missing:\n  " + "\n  ".join(missing)

    suites = list((template_dir / "tests").glob("test_*.py"))
    assert suites, (
        f"{_rel(template_dir)} has no tests/test_*.py suite. Every template proves "
        "its own secure defaults — see docs/TESTING.md."
    )


def test_template_has_a_real_test_suite(template_dir: Path) -> None:
    """Guard against an empty suite, which reads as coverage but is not.

    Three is not a magic number; it is the smallest count that forces an author
    past 'assert it parses' into the categories docs/TESTING.md asks for.
    """
    for suite in (template_dir / "tests").glob("test_*.py"):
        source = suite.read_text(encoding="utf-8")
        count = len(re.findall(r"^def test_", source, flags=re.MULTILINE))
        assert count >= 3, (
            f"{_rel(suite)} defines {count} test(s). Cover at least secure defaults, "
            "conditional wiring, and pass-through (docs/TESTING.md)."
        )


def test_metadata_is_valid(template_dir: Path) -> None:
    path = template_dir / "metadata.yaml"
    meta = yaml.safe_load(path.read_text(encoding="utf-8")) or {}

    missing = [k for k in REQUIRED_METADATA_KEYS if not meta.get(k)]
    assert not missing, f"{_rel(path)} is missing {', '.join(missing)}"
    assert meta["status"] in VALID_STATUSES, (
        f"{_rel(path)}: status {meta['status']!r} must be one of {'/'.join(VALID_STATUSES)}"
    )
    assert meta["group"] == template_dir.parent.name, (
        f"{_rel(path)}: group {meta['group']!r} does not match the directory "
        f"({template_dir.parent.name})"
    )
    assert "\n" not in str(meta["summary"]).strip(), (
        f"{_rel(path)}: summary must be a single line — it becomes one catalog row"
    )
    assert len(str(meta["summary"])) <= 110, (
        f"{_rel(path)}: summary is {len(str(meta['summary']))} chars; keep it under 110 "
        "so the catalog table stays readable"
    )


def test_readme_has_generated_doc_markers(template_dir: Path) -> None:
    readme = (template_dir / "README.md").read_text(encoding="utf-8")
    for marker in DOC_MARKERS:
        assert marker in readme, (
            f"{_rel(template_dir)}/README.md is missing {marker}. The parameter and "
            "output tables are generated by `./bin/cfn docs` between these markers."
        )
    assert "## Usage" in readme, (
        f"{_rel(template_dir)}/README.md needs a hand-written '## Usage' section above "
        "the generated tables — the tables say what the knobs are, not why."
    )


# --- template body ----------------------------------------------------------


def test_template_declares_format_version_and_description(any_template: Template) -> None:
    body = any_template.body
    assert body.get("AWSTemplateFormatVersion") == "2010-09-09", (
        f"{_rel(any_template.path)}: declare AWSTemplateFormatVersion: '2010-09-09'"
    )
    description = any_template.description.strip()
    assert description, f"{_rel(any_template.path)}: Description is required"
    assert description.endswith("."), (
        f"{_rel(any_template.path)}: Description should read as a sentence and end with '.'"
    )
    assert len(description) <= 1024, (
        f"{_rel(any_template.path)}: Description is {len(description)} chars; "
        "CloudFormation's limit is 1024"
    )


def test_template_is_within_cloudformation_limits(any_template: Template) -> None:
    size = any_template.path.stat().st_size
    assert size <= MAX_TEMPLATE_BYTES, f"{_rel(any_template.path)}: {size} bytes exceeds the 1 MB limit"
    assert len(any_template.resources) <= MAX_RESOURCES, "over the 500-resource limit"
    assert len(any_template.parameters) <= MAX_PARAMETERS, "over the 200-parameter limit"
    assert len(any_template.outputs) <= MAX_OUTPUTS, "over the 200-output limit"


def test_every_parameter_is_documented(any_template: Template) -> None:
    for name, spec in any_template.parameters.items():
        assert spec.get("Description"), (
            f"{_rel(any_template.path)}: parameter {name} has no Description. It shows up "
            "in the console, in `cfn params`, and in the generated README table."
        )
        assert spec.get("Type"), f"{_rel(any_template.path)}: parameter {name} has no Type"


def test_every_output_is_documented(any_template: Template) -> None:
    assert any_template.outputs, (
        f"{_rel(any_template.path)}: a template with no Outputs cannot be composed — "
        "expose the identifiers a caller needs to wire this to something else."
    )
    for name, spec in any_template.outputs.items():
        assert spec.get("Description"), (
            f"{_rel(any_template.path)}: output {name} has no Description"
        )


def test_parameters_are_grouped_for_the_console(any_template: Template) -> None:
    """Every parameter belongs to exactly one Interface ParameterGroup.

    A 30-parameter template with no groups is an unreadable console form and an
    unreadable README. Grouping is also a design check: a parameter that fits no
    group is usually a parameter that belongs in a different template.
    """
    if not any_template.parameters:
        return

    interface = any_template.metadata.get("AWS::CloudFormation::Interface") or {}
    groups = interface.get("ParameterGroups") or []
    assert groups, (
        f"{_rel(any_template.path)}: declare Metadata.AWS::CloudFormation::Interface "
        "with ParameterGroups — see docs/CONVENTIONS.md."
    )

    seen: dict[str, int] = {}
    for group in groups:
        for name in group.get("Parameters") or []:
            seen[name] = seen.get(name, 0) + 1

    ungrouped = sorted(set(any_template.parameters) - set(seen))
    assert not ungrouped, f"{_rel(any_template.path)}: parameters not in any group: {', '.join(ungrouped)}"

    duplicated = sorted(n for n, count in seen.items() if count > 1)
    assert not duplicated, f"{_rel(any_template.path)}: parameters in more than one group: {', '.join(duplicated)}"

    unknown = sorted(set(seen) - set(any_template.parameters))
    assert not unknown, f"{_rel(any_template.path)}: groups reference undeclared parameters: {', '.join(unknown)}"


def test_template_takes_a_name_prefix(any_template: Template) -> None:
    """The one parameter every template shares.

    Two stacks of the same template in one account collide on every physical
    name they create. A single, consistently named prefix is what makes
    `dev-`/`prod-` copies possible and what lets a stack pass its own prefix
    down to nested children without a translation layer.
    """
    assert "NamePrefix" in any_template.parameters, (
        f"{_rel(any_template.path)}: every template takes a NamePrefix parameter and "
        "derives its resource names from it (docs/INTERFACE.md)."
    )
    spec = any_template.param("NamePrefix")
    assert spec.get("AllowedPattern"), (
        f"{_rel(any_template.path)}: NamePrefix needs an AllowedPattern — it lands in "
        "resource names, and CloudFormation's error for an invalid name arrives 10 "
        "minutes into a rollback."
    )


def test_resource_logical_ids_are_alphanumeric(any_template: Template) -> None:
    bad = [rid for rid in any_template.resources if not re.fullmatch(r"[A-Za-z0-9]+", rid)]
    assert not bad, (
        f"{_rel(any_template.path)}: CloudFormation logical IDs must be alphanumeric: "
        f"{', '.join(bad)}"
    )


# --- examples ---------------------------------------------------------------


def test_example_parameters_match_the_template(template_dir: Path) -> None:
    """The example must actually deploy: every required parameter, nothing extra.

    This is the check that catches the most common rot in a template library —
    a parameter gets renamed and every example silently stops working, because
    nothing deploys them on a schedule.
    """
    t = Template(load_template(template_dir / "template.yaml"), template_dir / "template.yaml")
    path = template_dir / "examples" / "basic" / "parameters.json"
    entries = json.loads(path.read_text(encoding="utf-8"))

    assert isinstance(entries, list), (
        f"{_rel(path)}: must be a CloudFormation parameter file — a JSON list of "
        '{"ParameterKey": ..., "ParameterValue": ...}'
    )
    supplied = {}
    for entry in entries:
        assert set(entry) >= {"ParameterKey", "ParameterValue"}, (
            f"{_rel(path)}: each entry needs ParameterKey and ParameterValue"
        )
        supplied[entry["ParameterKey"]] = entry["ParameterValue"]

    unknown = sorted(set(supplied) - set(t.parameters))
    assert not unknown, f"{_rel(path)}: parameters not declared by the template: {', '.join(unknown)}"

    missing = sorted(set(t.required_parameters) - set(supplied))
    assert not missing, (
        f"{_rel(path)}: the example omits required parameters, so it cannot deploy: "
        f"{', '.join(missing)}"
    )


def test_example_values_satisfy_allowed_values(template_dir: Path) -> None:
    t = Template(load_template(template_dir / "template.yaml"), template_dir / "template.yaml")
    path = template_dir / "examples" / "basic" / "parameters.json"
    for entry in json.loads(path.read_text(encoding="utf-8")):
        name, value = entry["ParameterKey"], entry["ParameterValue"]
        allowed = t.allowed_values(name)
        if allowed:
            assert value in allowed, (
                f"{_rel(path)}: {name}={value!r} is not in AllowedValues {allowed}"
            )
        pattern = t.param(name).get("AllowedPattern")
        if pattern and isinstance(value, str):
            assert re.fullmatch(pattern, value), (
                f"{_rel(path)}: {name}={value!r} does not match AllowedPattern {pattern!r}"
            )


# --- environments -----------------------------------------------------------


def _environment_param_files() -> list[Path]:
    return sorted((REPO_ROOT / "environments").glob("*/params/*.json"))


@pytest.mark.parametrize(
    "param_file",
    _environment_param_files(),
    ids=[_rel(p) for p in _environment_param_files()],
)
def test_environment_parameters_target_a_real_template(param_file: Path) -> None:
    """An environment's parameter file must name a template and satisfy it.

    `bin/cfn deploy` resolves `environments/<env>/params/<slug>.json` by the
    target's slug. A typo there means the deploy silently falls back to template
    defaults, which is exactly the kind of quiet wrong that reaches production.
    """
    slug = param_file.stem
    candidates = [
        REPO_ROOT / "stacks" / slug / "template.yaml",
        *(REPO_ROOT / "templates").glob(f"*/{slug}/template.yaml"),
    ]
    target = next((c for c in candidates if c.exists()), None)
    assert target is not None, (
        f"{_rel(param_file)} names '{slug}', which is neither a stack nor a template. "
        "Rename the file to match its deploy target."
    )

    t = Template(load_template(target), target)
    supplied = {e["ParameterKey"]: e["ParameterValue"] for e in json.loads(param_file.read_text())}

    unknown = sorted(set(supplied) - set(t.parameters))
    assert not unknown, f"{_rel(param_file)}: not declared by {_rel(target)}: {', '.join(unknown)}"

    missing = sorted(set(t.required_parameters) - set(supplied))
    assert not missing, f"{_rel(param_file)}: missing required parameters: {', '.join(missing)}"


def _environment_configs() -> list[Path]:
    return sorted((REPO_ROOT / "environments").glob("*/env.json"))


@pytest.mark.parametrize(
    "env_config",
    _environment_configs(),
    ids=[_rel(p) for p in _environment_configs()],
)
def test_environment_config_is_complete(env_config: Path) -> None:
    config = json.loads(env_config.read_text(encoding="utf-8"))
    for key in ("region", "stack_prefix", "tags"):
        assert config.get(key), f"{_rel(env_config)}: '{key}' is required"
    assert isinstance(config["tags"], dict), f"{_rel(env_config)}: 'tags' must be an object"
    assert config.get("capabilities"), (
        f"{_rel(env_config)}: 'capabilities' is required — templates that create IAM "
        "roles need CAPABILITY_IAM or CAPABILITY_NAMED_IAM, and nested stacks need "
        "CAPABILITY_AUTO_EXPAND."
    )
