#!/usr/bin/env python3
"""Generate the parameter / output / resource tables in every README.

This is `terraform-docs` for CloudFormation. Tables are written between the
`<!-- BEGIN_CFN_DOCS -->` and `<!-- END_CFN_DOCS -->` markers; the hand-written
Usage section above them is never touched.

Generating rather than hand-writing matters for one reason: a parameter table
that drifts from the template is worse than none, because a reader trusts it.
`--check` runs in CI so drift is a failed build rather than a support question.

    scripts/gen_docs.py           # rewrite every README in place
    scripts/gen_docs.py --check   # exit 1 if any README is out of date
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tests"))

from cfn_loader import Template, load_template  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
BEGIN = "<!-- BEGIN_CFN_DOCS -->"
END = "<!-- END_CFN_DOCS -->"

GENERATED_NOTE = (
    "<!-- Generated by `./bin/cfn docs`. Do not edit between these markers. -->"
)


def directories() -> list[Path]:
    templates = sorted(
        p.parent for p in (REPO_ROOT / "templates").glob("*/*/template.yaml")
    )
    stacks = sorted(p.parent for p in (REPO_ROOT / "stacks").glob("*/template.yaml"))
    return templates + stacks


def cell(value: Any) -> str:
    """Render a value for a Markdown table cell.

    Pipes break table layout and newlines break the row entirely, so both are
    neutralised. Structured defaults (rare, but legal in a `CommaDelimitedList`)
    render as compact JSON rather than Python repr.
    """
    if value is None:
        return ""
    if isinstance(value, bool):
        text = "true" if value else "false"
    elif isinstance(value, (dict, list)):
        text = json.dumps(value, separators=(",", ":"))
    else:
        text = str(value)
    return text.replace("|", "\\|").replace("\n", " ").strip()


def parameter_table(t: Template) -> list[str]:
    if not t.parameters:
        return ["_This template takes no parameters._"]

    lines = [
        "| Parameter | Description | Type | Default |",
        "|-----------|-------------|------|---------|",
    ]
    for name, spec in t.parameters.items():
        description = cell(spec.get("Description", ""))
        if spec.get("AllowedValues"):
            allowed = ", ".join(f"`{cell(v)}`" for v in spec["AllowedValues"])
            description = f"{description}<br>Allowed: {allowed}"
        if spec.get("NoEcho"):
            description = f"{description}<br>**NoEcho** — never echoed back by the API."

        if "Default" in spec:
            default = f"`{cell(spec['Default'])}`" if spec["Default"] != "" else '`""`'
            label = f"`{name}`"
        else:
            default = "**required**"
            label = f"`{name}`"

        lines.append(f"| {label} | {description} | `{cell(spec.get('Type'))}` | {default} |")
    return lines


def output_table(t: Template) -> list[str]:
    if not t.outputs:
        return ["_This template has no outputs._"]

    lines = [
        "| Output | Description | Exported as |",
        "|--------|-------------|-------------|",
    ]
    for name, spec in t.outputs.items():
        export = spec.get("Export", {}).get("Name") if isinstance(spec.get("Export"), dict) else None
        lines.append(
            f"| `{name}` | {cell(spec.get('Description', ''))} | "
            f"{'`' + cell(export) + '`' if export else '—'} |"
        )
    return lines


def resource_table(t: Template) -> list[str]:
    """What the template actually creates, and what is conditional.

    The conditional column is the one readers need: it answers "what do I get if
    I change nothing?" without reading the whole template.
    """
    if not t.resources:
        return ["_This template creates no resources._"]

    lines = [
        "| Logical ID | Type | Created when |",
        "|------------|------|--------------|",
    ]
    for rid, resource in t.resources.items():
        condition = resource.get("Condition")
        when = f"`{condition}`" if condition else "always"
        lines.append(f"| `{rid}` | `{cell(resource.get('Type'))}` | {when} |")
    return lines


def render(t: Template) -> str:
    sections: list[str] = [GENERATED_NOTE, ""]
    sections += ["### Parameters", ""] + parameter_table(t) + [""]
    sections += ["### Outputs", ""] + output_table(t) + [""]
    sections += ["### Resources", ""] + resource_table(t)
    return "\n".join(sections)


def splice(readme: str, block: str, path: Path) -> str:
    try:
        head, rest = readme.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
    except ValueError:
        raise SystemExit(
            f"{path}: missing the {BEGIN} / {END} markers. Every template README "
            "carries them — copy the shape from templates/_template/README.md."
        )
    return f"{head}{BEGIN}\n{block}\n{END}{tail}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any README is out of date instead of rewriting it",
    )
    args = parser.parse_args()

    stale: list[str] = []
    written = 0

    for directory in directories():
        if directory.name == "_template":
            continue
        readme_path = directory / "README.md"
        if not readme_path.exists():
            raise SystemExit(f"{directory}: no README.md")

        t = Template(load_template(directory / "template.yaml"), directory / "template.yaml")
        current = readme_path.read_text(encoding="utf-8")
        updated = splice(current, render(t), readme_path)

        if current == updated:
            continue
        if args.check:
            stale.append(str(readme_path.relative_to(REPO_ROOT)))
            continue
        readme_path.write_text(updated, encoding="utf-8")
        written += 1

    if stale:
        print(
            "these READMEs are out of date — run `./bin/cfn docs` and commit:\n  "
            + "\n  ".join(stale),
            file=sys.stderr,
        )
        return 1

    print("docs up to date" if not written else f"docs regenerated ({written} README(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
